# Generated by Django 4.2.5 on 2023-09-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=155, verbose_name='Цена')),
                ('country_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/auto')),
                ('mobile', models.CharField(max_length=15, verbose_name='Телефон')),
                ('user_id', models.CharField(max_length=155, verbose_name='Юзэр')),
            ],
        ),
    ]
